In [2]:
import numpy as np


#### Ejecicio #1:    Operaciones Matriciales
Dada una matriz en formato numpy array, donde cada fila de la matriz representa un vector matemático: 
* Computar las normas l0, l1, l2, l-infinito
    * l0: número de elementos diferentes a cero en el vector
    * l1-l2: 
    ![](https://latex.codecogs.com/svg.latex?%7B%5Ccolor%7BOrange%7D%20%5Cleft%20%5C%7C%20x%20%5Cright%20%5C%7C_%7Bp%7D%20%3D%20%5Cleft%20%28%20%5Csum_%7B1%7D%5E%7Bn%7D%20%5Cleft%20%7C%20x_%7Bi%7D%20%5Cright%20%7C%5Ep%20%5Cright%20%29%5E%7B%5Ctfrac%7B1%7D%7Bp%7D%7D%7D)
    * l-infinito:
     ![](https://latex.codecogs.com/svg.latex?%7B%5Ccolor%7BOrange%7D%20%5Cleft%20%5C%7C%20x%20%5Cright%20%5C%7C_%7B%5Cinfty%7D%20%3D%20max_%7Bi%7D%20%5Cleft%20%7C%20x_%7Bi%7D%20%5Cright%20%7C%7D)

In [2]:
matriz = np.array([[1,0,3,4],[5,6,0,8,],[0,10,11,12],[13,14,0,16]])

In [3]:
print(matriz)

[[ 1  0  3  4]
 [ 5  6  0  8]
 [ 0 10 11 12]
 [13 14  0 16]]


In [4]:
# Norma L0
# Una forma de hacerlo
norma_0 = np.count_nonzero(matriz)

# Otra forma de hacerlo
norma_0_ = np.sum(matriz != 0)

In [5]:
print("Norma L0: ", norma_0)
print("Norma L0: ", norma_0_)

Norma L0:  12
Norma L0:  12


In [6]:
# L1-L2

# L1
norma_1 = np.linalg.norm(matriz,1)
print("Norma L1: ", norma_1)

Norma L1:  40.0


In [7]:
# L2
norma_2 = np.linalg.norm(matriz,2)
print("Norma L2: ", norma_2)

Norma L2:  31.333360671706163


In [8]:
print("Norma 1 - Noma 2 de la matriz: ", norma_1 - norma_2)

Norma 1 - Noma 2 de la matriz:  8.666639328293837


In [9]:
# l-infinito
norma_infinito = np.linalg.norm(matriz,np.inf)
print("Norma infinito: ", norma_infinito)

Norma infinito:  43.0


#### Ejecicio #2:    Sorting :house:
Dada una matriz en formato numpy array, donde cada fila de la matriz representa un vector matemático, se requiere computar la norma l2 de cada vector.
Una vez obtenida la norma, se debe ordenar las mísmas de mayor a menor. Finalmente, obtener la matriz original ordenada por fila según la norma l2.

In [10]:
A = np.array([[1, -2, 3], [-4, 5, -6], [7, -8, 9]])

In [11]:
A

array([[ 1, -2,  3],
       [-4,  5, -6],
       [ 7, -8,  9]])

In [12]:
vec_l2 = np.array([])

In [13]:
for rows in A:
    # print(rows)
    vec_l2 = np.append(vec_l2, np.linalg.norm(rows))

In [14]:
vec_l2

array([ 3.74165739,  8.77496439, 13.92838828])

In [15]:
mat_norm2 = np.zeros((2,3))

In [16]:
mat_norm2.shape

(2, 3)

In [17]:
mat_norm2[0] = vec_l2[0:3]

In [18]:
mat_norm2

array([[ 3.74165739,  8.77496439, 13.92838828],
       [ 0.        ,  0.        ,  0.        ]])

In [19]:
for i in range(3):
    mat_norm2[1, i] = i

In [20]:
mat_norm2

array([[ 3.74165739,  8.77496439, 13.92838828],
       [ 0.        ,  1.        ,  2.        ]])

In [21]:
# Obtener los índices que ordenarían la fila 1 en orden descendente
sorted_indices = np.argsort(mat_norm2[1])[::-1]

In [22]:
# Reordenar todas las filas de la matriz de acuerdo con estos índices
sorted_mat_norm2 = mat_norm2[:, sorted_indices]

In [23]:
print(sorted_mat_norm2)

[[13.92838828  8.77496439  3.74165739]
 [ 2.          1.          0.        ]]


In [24]:
A.shape

(3, 3)

In [25]:
reordenada = A[sorted_indices]

In [26]:
reordenada

array([[ 7, -8,  9],
       [-4,  5, -6],
       [ 1, -2,  3]])

#### Ejecicio #3:    Indexing :house:
El objetivo es construir un índice para identificadores de usuarios, es decir _id2idx_ e _idx2id_.
Para ello crear una clase, donde el índice se genere en el constructor. Armar métodos _get_users_id_ y _get_users_idx_.

* Identificadores de usuarios : users_id = [15, 12, 14, 10, 1, 2, 1]
* Índice de usuarios : users_id = [0, 1, 2, 3, 4, 5, 4]
```
id2idx =  [-1     4     5    -1    -1    -1     -1    -1    -1    -1     3     -1      1    -1     2     0]
          [ 0     1     2     3     4     5      6     7     8     9    10     11     12    13    14    15]

id2idx[15] -> 0 ; id2idx[12] -> 1 ; id2idx[3] -> -1
idx2id[0] -> 15 ; idx2id[4] -> 1
```

In [27]:
import numpy as np

In [28]:
class UserIndex:
    def __init__(self, usuarios_id):
        #self.user_index = {}
        #maximo de un array de numpy
        user_id_min = np.min(usuarios_id) # minimos
        user_id_max = np.max(usuarios_id) # maximos
        #array_id_idx = np.array([np.full(user_id_max+1, -1), np.arange(user_id_min-1, user_id_max+1)]) # array de minimos-1 a maximos+1
        self.array_id_idx = np.array(np.full(user_id_max+1, -1))
        print(self.array_id_idx)

        #recorro los usuarios_id
        for i in range(len(usuarios_id)):
            if self.array_id_idx[usuarios_id[i]] == -1:
                self.array_id_idx[usuarios_id[i]] = i

        print(self.array_id_idx)
        


    def get_users_id(self, idx):
        indice = np.where(self.array_id_idx == idx)
        return indice

    def get_users_idx(self, id):
        id = self.array_id_idx[id]
        return id

In [29]:
usuarios_id = [15, 12, 14, 10, 1, 2, 1]
usuarios_indices = UserIndex(usuarios_id)

[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[-1  4  5 -1 -1 -1 -1 -1 -1 -1  3 -1  1 -1  2  0]


In [30]:
print(usuarios_indices.get_users_id(0))  # Imprime: 12345

(array([15]),)


In [31]:
print(usuarios_indices.get_users_idx(14))

2


#### Ejecicio #4:    Precision, Recall, Accuracy :house:
En los problemas de clasificación, se cuenta con dos arreglos, la **verdad** (ground truth) y la **predicción** (prediction). 
Cada elemento de los arreglos puede tomar dos valores: _True_ (representado por 1) y _False_ (representado por 0). 
Por lo tanto, se pueden definir cuatro variables:
* True Positive (TP): la verdad es 1 y la predicción es 1.
* True Negative (TN): la verdad es 0 y la predicción es 0.
* False Negative (FN): la verdad es 1 y la predicción es 0.
* False Positive (FP): la verdad es 0 y la predicción es 1.

A partir de esas cuatro variables, se definen las siguientes métricas:
* Precision = TP / (TP + FP)
* Recall = TP / (TP + FN)
* Accuracy = (TP + TN) / (TP + TN + FP + FN)

Para los siguientes arreglos, representando la **verdad** y la **predicción**,
calcular las métricas anteriores con operaciones vectorizadas en NumPy.
* truth = [1,1,0,1,1,1,0,0,0,1]
* prediction = [1,1,1,1,0,0,1,1,0,0]


In [32]:
# 
truth = np.array([1, 1, 0, 1, 1, 1, 0, 0, 0, 1])
prediction = np.array([1, 1, 1, 1, 0, 0, 1, 1, 0, 0])


In [33]:
TP = np.sum(np.logical_and(truth == 1, prediction == 1))
TN = np.sum(np.logical_and(truth == 0, prediction == 0))
FN = np.sum(np.logical_and(truth == 1, prediction == 0))
FP = np.sum(np.logical_and(truth == 0, prediction == 1))


In [39]:
print("TP: ", TP)
print("TN: ", TN)
print("FN: ", FN)
print("FP: ", FP)


TP:  3
TN:  1
FN:  3
FP:  3


In [35]:
precision = TP / (TP + FP)
print("Precision: ", precision)

Precision:  0.5


In [36]:
recall = TP / (TP + FN)
print("Recall: ", recall)

Recall:  0.5


In [37]:
acurracy = (TP + TN) / (TP + TN + FP + FN)
print("Acurracy: ", acurracy)

Acurracy:  0.4


#### Ejecicio #5:    Average Query Precision :house:
En information retrieval o search engines, en general contamos con queries “q” y para cada “q” una lista de documentos que son verdaderamente relevantes. 
Para evaluar un search engine, es común utilizar la métrica **average query precision**.
Tomando de referencia el siguiente ejemplo, calcular la métrica con NumPy utilizando operaciones vectorizadas.
```
q_id =             [1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4]
predicted_rank =   [0, 1, 2, 3, 0, 1, 2, 0, 1, 2, 3, 4, 0, 1, 2, 3]
truth_relevance =  [T, F, T, F, T, T, T, F, F, F, F, F, T, F, F, T] 
```
* Precision para q_id 1 = 2 / 4
* Precision para q_id 2 = 3 / 3
* Precision para q_id 3 = 0 / 5
* Precision para q_id 4 = 2 / 4

**_average query precision_** = ((2/4) + (3/3) + (0/5) + (2/4)) / 4

##### Explicación paso a paso

Los datos proporcionados se pueden interpretar como:

- q_id representa el ID de la consulta.
- predicted_rank representa el rango predicho de los documentos para cada consulta.
- truth_relevance indica si el documento es relevante (T) o no (F).

Usando estos datos, podemos calcular la precisión para cada consulta:

1. Para q_id 1, tenemos 2 documentos relevantes (T) de 4 recuperados, por lo que la precisión es 0.5.
2. Para q_id 2, tenemos 3 documentos relevantes (T) de 3 recuperados, por lo que la precisión es 1.0.
3. Para q_id 3, no tenemos documentos relevantes (T) de 6 recuperados, por lo que la precisión es 0.
4. Para q_id 4, tenemos 2 documentos relevantes (T) de 4 recuperados, por lo que la precisión es 0.5.

Finalmente, calculamos la average query precision tomando el promedio de las precisiones individuales:

**_average query precision_** = ((2/4) + (3/3) + (0/5) + (2/4)) / 4


In [33]:
import numpy as np

q_id = np.array([1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4]) 
truth_relevance = np.array(['T', 'F', 'T', 'F', 'T', 'T', 'T', 'F', 'F', 'F', 'F', 'F', 'T', 'F', 'F', 'T'])

truth_relevance_booleano = np.where(truth_relevance == 'T', 1, 0)
#truth_relevance_booleano = truth_relevance == 'T'

unicos_q_id = np.unique(q_id)

print("Ids unicos:",unicos_q_id)
print("Vector de Truth pasados a 1 o 0:",truth_relevance_booleano)
print("\n")

precision_q_id = np.zeros(len(unicos_q_id))
# print(precision_q_id)
# print("#################")

izq = 0
der = 0
suma = 0
for i in range(len(unicos_q_id)):
    #print("id:",i+1)
    cantidad_unicos = np.count_nonzero(q_id == i+1) # cuento cuantos hay
    #print("Cantidad de ids unicos: ", cantidad_unicos)
    izq = der
    der = izq+cantidad_unicos

    # print("Izq:",izq, "Der:",der)
    # print("Cada Trues y False", truth_relevance_booleano[izq:der])    
    for s in range(izq, der):
        suma = suma + truth_relevance_booleano[s]
    
    #print("Suma: ", suma)
    precision_q_id[i] = suma / cantidad_unicos
    #print("\n")

    suma = 0


# print("4 primeros", truth_relevance_booleano[0:4])
# print("3 segundos", truth_relevance_booleano[4:7])
# print("3 segundos", truth_relevance_booleano[7:12])
# print("4 segundos", truth_relevance_booleano[12:16])

print("Precision por id: ", precision_q_id)
average_precision = np.mean(precision_q_id)
print("Average Precision: ", average_precision)

Ids unicos: [1 2 3 4]
Vector de Truth pasados a 1 o 0: [1 0 1 0 1 1 1 0 0 0 0 0 1 0 0 1]


Precision por id:  [0.5 1.  0.  0.5]
Average Precision:  0.5


#### Ejecicio #6:    Distancia a Centroides
Dada una nube de puntos _X_ y centroides _C_, obtener la distancia entre
cada vector _X_ y los centroides utilizando operaciones vectorizadas y broadcasting en NumPy.
Utilizar como referencia los siguientes valores:
```
X = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
C = [[1, 0, 0], [0, 1, 1]]   

#### Ejecicio #7:    Etiquetar Cluster
Obtener para cada fila en _X_, el índice de la fila en _C_ con distancia euclídea más pequeña. 
Es decir, para cada fila en _X_, determinar a qué cluster pertenece en C.
_Hint_: usar np.argmin.

#### Ejercicio #8:   Implementación Básica de K-means
K-means es uno de los algoritmos más básicos en Machine Learning no supervisado.
Es un algoritmo de clusterización, que agrupa datos que comparten características similares.
Recordemos que entendemos datos como _n_ realizaciones del vector aleatorio _X_.

El algoritmo funciona de la siguiente manera:
1. El usuario selecciona la cantidad de clusters a crear _n_.
2. Se seleccionan _n_ elementos aleatorios de _X_ como posiciones iniciales del los centroides _C_.
3. Se calcula la distancia entre todos los puntos en _X_ y todos los puntos en _C_.
4. Para cada punto en _X_ se selecciona el centroide más cercano de _C_.
5. Se recalculan los centroides _C_ a partir de usar las filas de _X_ que pertenecen a cada centroide. 
6. Se itera entre 3 y 5 una cantidad fija de veces o hasta que la posición de los centroides no cambie dada una tolerancia.

Se debe por lo tanto implementar la función k_means(X, n) de manera tal que, al finalizar, devuelva la posición de los centroides
y a qué cluster pertenece cada fila de _X_. 

_Hint_: para (2) utilizar funciones de np.random, para (3) y (4) usar los ejercicios anteriores, 
para (5) es válido utilizar un for. Iterar 10 veces entre (3) y (5).  

#### Ejercicio #9:   Computar Métricas con \_\_call__ :house:
En problemas de machine learning, es muy común que para cada predicción que obtenemos en nuestro dataset de verificacion y evaluacion, almacenemos en arreglos de numpy el resultado de dicha predicción, junto con el valor verdadero y parámetros auxiliares (como el ranking de la predicción y el query id). 

Luego de obtener todas las predicciones, podemos utilizar la información almacenada en los arreglos de numpy, para calcular todas las métricas que queremos medir en nuestro sistema. 

Una buena práctica para implementar esto en Python, es crear clases que hereden de una clase Metric “base” y que cada métrica implemente el método \_\_call__.

Utilizar herencia, operador \_\_call__ y _kwargs_, para escribir un programa que permita calcular todas las métricas de los ejercicios anteriores mediante un for.

#### Ejercicio #10:   Dataset a NumPy Estructurado - Patrón de Diseño Singleton :house:
Para éste ejercicio vamos a descargar un dataset de Kaggle. Es recomendable que se creen una cuenta porque es un lugar de donde potencialmente vamos a descargar muchos recursos.

Pueden descargar el dataset desde [aquí](https://www.kaggle.com/rounakbanik/the-movies-dataset/data?select=ratings.csv).

El objetivo del ejercicio es crear una clase que permita realizar las siguientes funciones sobre el dataset:
* Crear la estructura de un structured numpy array para el dataset.
* Leer el csv, almacenar la información en el array estructurado.
* Guardar el array estructurado en formato .pkl.
* Crear una instancia singleton del array estructurado (utilizando \_\_new__ e \_\_init__).
* Al crear la instancia, si se encuentra el .pkl cargar desde el pkl. Si el .pkl no está, comenzar por transformar el .csv en .pkl y luego levantar la información.
* Encontrar una forma de optimizar la operación usando generators [opcional].
 