In [5]:
import numpy as np
import sys

### Creación de array

In [6]:
# Creación de arreglos
np.array([1,2,3])

array([1, 2, 3])

In [7]:
a = np.ones(3)
b = np.zeros(3)
c = np.random.rand(3)

In [8]:
a,b,c

(array([1., 1., 1.]),
 array([0., 0., 0.]),
 array([0.00491277, 0.02074225, 0.53586073]))

In [9]:
arreglo_2d = np.array([[1,2],
        [3,4]])

In [10]:
np.random.randint(size=(1,2,3), low = 0, high = 10) 


array([[[3, 8, 3],
        [4, 6, 5]]])

In [11]:
a = np.ones((3,2))
b = np.zeros((3, 2))
c = np.random.random((3, 2))

In [12]:
a, b, c

(array([[1., 1.],
        [1., 1.],
        [1., 1.]]),
 array([[0., 0.],
        [0., 0.],
        [0., 0.]]),
 array([[0.32246587, 0.15028968],
        [0.37439954, 0.06956258],
        [0.08965991, 0.68397726]]))

In [13]:
np.ones((2,2))*7

array([[7., 7.],
       [7., 7.]])

In [14]:
np.full((2,2), np.nan)

array([[nan, nan],
       [nan, nan]])

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Atributos Principales

In [16]:
a = np.array(    [
                [[1, 2],[3, 4]],
                [[5, 6],[7, 8]]    
                ])

In [17]:
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [18]:
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [19]:
#N° de dimensiones
a.ndim

3

In [20]:
# estructura del arreglo
a.shape

(2, 2, 2)

In [21]:
#Cantidad de elementos de a
a.size

8

In [22]:
# Tipo de dato de cada elemento
a.dtype

dtype('int64')

In [23]:
#Cantidad de bytees que ocupa en la memoria
a.nbytes

64

### Operaciones aritméticas

In [24]:
x = [[1,2],[3,4]]
y = [[5,6],[7,8]]

In [25]:
print(x)
print(y)

[[1, 2], [3, 4]]
[[5, 6], [7, 8]]


In [26]:
x,y

([[1, 2], [3, 4]], [[5, 6], [7, 8]])

In [27]:
# Son listas
x+y

[[1, 2], [3, 4], [5, 6], [7, 8]]

In [28]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [29]:
%%timeit
x+y

321 ns ± 3.13 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [30]:
%%timeit
np.add(x,y)

333 ns ± 0.617 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [31]:
print(x * y)
print(np.multiply(x,y))

print(x / y)
print(np.divide(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [32]:
data = np.array([[1, 2],[3, 4]])
print(data)

[[1 2]
 [3 4]]


In [33]:
ones = np.ones((2, 2))
print(ones)

[[1. 1.]
 [1. 1.]]


In [34]:
data + ones

array([[2., 3.],
       [4., 5.]])

In [35]:
data = np.array([1, 2])
ones = np.ones(2)
print(data - ones)
print(data * data)
print(data / data)

[0. 1.]
[1 4]
[1. 1.]


In [36]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

In [37]:
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

[29 67]
[29 67]
[29 67]


In [38]:
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


### Agregación

In [39]:
a = np.array([1, 2, 3, 4])

In [40]:
a.mean()

2.5

In [41]:
a.min()

1

In [42]:
a.max()

4

In [43]:
a.sum()

10

In [44]:
a.std()

1.118033988749895

### Funciones universales

In [45]:
[x for x in [1,2,3]]

[1, 2, 3]

In [46]:
np.arange(3)

array([0, 1, 2])

In [47]:
x = np.arange(3)

In [48]:
np.arange(30.)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29.])

In [49]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interva

In [50]:
x

array([0, 1, 2])

In [51]:
np.exp(x)

array([1.        , 2.71828183, 7.3890561 ])

In [52]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356])

In [53]:
np.cumsum(x)

array([0, 1, 3])

In [54]:
x = [1, 2, 3, 3, 7, 5, 54, 6, 1, 4]

In [55]:
np.sort(x)

array([ 1,  1,  2,  3,  3,  4,  5,  6,  7, 54])

In [56]:
np.max(x), np.argmax(x)

(54, 6)

In [57]:
np.argsort(x)

array([0, 8, 1, 2, 3, 9, 5, 7, 4, 6])

In [58]:
np.bincount(x)

array([0, 2, 1, 2, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

### Indexing, slicing

In [59]:
a = np.arange(10)**3

In [60]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [61]:
a[2]

8

In [62]:
len(a)

10

In [63]:
a[9]

729

In [64]:
b = [  0,   1,   8,  27,  64, 125, 216, 343, 512, 729]

b[2:5]

[8, 27, 64]

In [65]:
a[2:5]

array([ 8, 27, 64])

In [66]:
a[2],a[5]

(8, 125)

In [67]:
a[:6:2]

array([ 0,  8, 64])

In [68]:
a[ : :-1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [69]:
b = np.arange(16).reshape((4,4))

In [70]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [71]:
b[2,3]

11

In [72]:
b[0:5, 1]

array([ 1,  5,  9, 13])

In [73]:
b[ : ,1]

array([ 1,  5,  9, 13])

In [74]:
b[-1]

array([12, 13, 14, 15])

In [75]:
aux = np.arange(6) +1
aux

array([1, 2, 3, 4, 5, 6])

In [76]:
aux = aux.reshape(3,2)
aux

array([[1, 2],
       [3, 4],
       [5, 6]])

In [77]:
aux[1:]

array([[3, 4],
       [5, 6]])

### Manipulación de estructura

In [78]:
a = np.arange(12).reshape((3, 4))

In [79]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [80]:
# Sin modificar el array original
print(a.ravel())
print(a.reshape((6,2)))
print(a.T)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [81]:
a.reshape(2, -1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [82]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [83]:
# Modifica el array original
a.resize((6, 2))

In [84]:
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

### Copy Vs. View

In [85]:
a = np.arange(12).reshape((3, 4))

In [86]:
a,b

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]))

In [87]:
b = a

In [88]:
b is a

True

In [89]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
print(hex(id(a)))
print(hex(id(b)))

0x7f0ea0513030
0x7f0ea0513030


In [91]:
def f(x):
    print(id(x))

print(id(a))
f(a)

139700795945008
139700795945008


### View

In [92]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [93]:
c = a.view()

In [94]:
c is a

False

In [95]:
c.base

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [96]:
c.flags.owndata

False

In [97]:
c = c.reshape((3, 4))

In [98]:
c.flags.owndata

False

In [99]:
c[1, 2] = 100

In [100]:
a

array([[  0,   1,   2,   3],
       [  4,   5, 100,   7],
       [  8,   9,  10,  11]])

In [101]:
# Slicing también devuelve un view o shallow copy
s = a[ : , 1:3]
print(s)
s[:] = 400

[[  1   2]
 [  5 100]
 [  9  10]]


In [102]:
a

array([[  0, 400, 400,   3],
       [  4, 400, 400,   7],
       [  8, 400, 400,  11]])

In [103]:
s.flags.owndata

False

### Copy

In [106]:
d = a.copy()

In [107]:
d is a

False

In [108]:
# Veo si d es vista de a
d.base is a

False

In [109]:
d.flags.owndata

True

In [110]:
d[1, :] = 100

In [111]:
d

array([[  0, 400, 400,   3],
       [100, 100, 100, 100],
       [  8, 400, 400,  11]])

In [112]:
a

array([[  0, 400, 400,   3],
       [  4, 400, 400,   7],
       [  8, 400, 400,  11]])

In [113]:
print(hex(id(a)))
print(hex(id(d)))

0x7f0ea0513030
0x7f0ea0515090


### Indexing con arrays

In [115]:
a = np.arange(12)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [116]:
i = np.array([1, 1, 3, 8, 5])
a[i]

array([ 1,  1,  9, 64, 25])

In [117]:
j = np.array([[3, 4], [9, 7]])
a[j]

array([[ 9, 16],
       [81, 49]])

In [118]:
palette = np.array([[0, 0, 0], [255, 0, 0], [0, 255, 0], [0, 0, 255], [255, 255, 255]])

image = np.array([[0, 1, 2, 0], [0, 3, 4, 0]])

In [119]:
palette[image]

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

### Masking

In [120]:
a = np.arange(4)

In [121]:
a

array([0, 1, 2, 3])

In [123]:
a[[True,False,False,True]]

array([0, 3])

In [124]:
a >= 2

array([False, False,  True,  True])

In [125]:
a[a >= 2]

array([2, 3])

In [127]:
a[a > a.mean()]

array([2, 3])

In [128]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

### Strutured dtype

In [129]:
structure = [('word',np.dtype('U60')),
            ('embedding', np.float32, (4,))]
structure = np.dtype(structure)
a = np.empty(10, dtype=structure)


In [130]:
a

array([('', [0., 0., 0., 0.]), ('', [0., 0., 0., 0.]),
       ('', [0., 0., 0., 0.]), ('', [0., 0., 0., 0.]),
       ('', [0., 0., 0., 0.]), ('', [0., 0., 0., 0.]),
       ('', [0., 0., 0., 0.]), ('', [0., 0., 0., 0.]),
       ('', [0., 0., 0., 0.]), ('', [0., 0., 0., 0.])],
      dtype=[('word', '<U60'), ('embedding', '<f4', (4,))])

In [131]:
a[0]["word"] = "hola"
a[0]["embedding"] = [1, 2, 3, 4]
a[1]["word"] = "chau"
a[1]["embedding"] = [-1, -2, -3, -4]

In [132]:
a

array([('hola', [ 1.,  2.,  3.,  4.]), ('chau', [-1., -2., -3., -4.]),
       ('', [ 0.,  0.,  0.,  0.]), ('', [ 0.,  0.,  0.,  0.]),
       ('', [ 0.,  0.,  0.,  0.]), ('', [ 0.,  0.,  0.,  0.]),
       ('', [ 0.,  0.,  0.,  0.]), ('', [ 0.,  0.,  0.,  0.]),
       ('', [ 0.,  0.,  0.,  0.]), ('', [ 0.,  0.,  0.,  0.])],
      dtype=[('word', '<U60'), ('embedding', '<f4', (4,))])

### Funciones Útiles

In [134]:
a = np.array([[1.0,2.0],[3.0,4.0]])

In [135]:
a

array([[1., 2.],
       [3., 4.]])

In [136]:
# Inversa de una matriz
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [138]:
np.trace(a)

5.0

In [139]:
#Calcula los autovalores y autovectores de una matriz.
np.linalg.eig(a)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [140]:
a = [1, 1, 5, 6]

In [141]:
# devuelve los valores únicos de un array
np.unique(a)

array([1, 5, 6])

In [144]:
# es una herramienta en NumPy que genera una secuencia de números equiespaciados entre dos valores dados. 
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [145]:
# devuelve una secuencia de números espaciados uniformemente dentro de un intervalo especificado.
np.arange(0, 1, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])