In [3]:
import numpy as np
import sys


In [4]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
c = 2.0
print("Sin broadcasting: ", a * b)
print("Con broadcasting: ", a * c)

Sin broadcasting:  [2. 4. 6.]
Con broadcasting:  [2. 4. 6.]


In [5]:
d = np.arange(500000)
e = np.full(500000, 2.0)
f = 2.0

In [17]:
%time d * e

CPU times: user 2.21 ms, sys: 726 µs, total: 2.93 ms
Wall time: 2.02 ms


array([0.00000e+00, 2.00000e+00, 4.00000e+00, ..., 9.99994e+05,
       9.99996e+05, 9.99998e+05])

In [18]:
%time d * f

CPU times: user 1.7 ms, sys: 0 ns, total: 1.7 ms
Wall time: 1.09 ms


array([0.00000e+00, 2.00000e+00, 4.00000e+00, ..., 9.99994e+05,
       9.99996e+05, 9.99998e+05])

### Reglas de broadcasting

In [19]:
x = np.arange(4)
xx = x.reshape(4,1)
y = np.ones(4)
z = np.ones((3,4))

print(x.shape, xx.shape, y.shape, z.shape)

(4,) (4, 1) (4,) (3, 4)


In [21]:
np.array([[1],[2],[3],[4]]).shape

(4, 1)

In [23]:
print(x)
print(y)

[0 1 2 3]
[1. 1. 1. 1.]


In [22]:
x + y # (4,) + (4,)

array([1., 2., 3., 4.])

In [24]:
print(xx, y)

[[0]
 [1]
 [2]
 [3]] [1. 1. 1. 1.]


In [26]:
print(xx + y)
print((xx+y).shape)

[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]
(4, 4)


In [29]:
print(x,'\n\n', z)

[0 1 2 3] 

 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [30]:
print(x + z)
print((x + z).shape)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]
(3, 4)


In [34]:
## Podemos verificar si una serie de arreglos pueden ser "broadcasteados" en NumPy. ¡No se suele usar!
np.broadcast(*(x, y))

In [37]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
print(a)
print(a.shape)
# np.newaxis agrega una nueva dimensión (1).
print(a[:,np.newaxis].shape)
a[:,np.newaxis] + b # equivalente a a[:,None] + b

[ 0. 10. 20. 30.]
(4,)
(4, 1)


array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])